// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDc7TbSZnlZHp2muPb3HFa0l_OVGbTMsXA',
    appId: '1:702436046817:web:ce2b1b9bff9958f7e0c4a0',
    messagingSenderId: '702436046817',
    projectId: 'desarrollocode',
    authDomain: 'desarrollocode.firebaseapp.com',
    databaseURL: 'https://desarrollocode-default-rtdb.firebaseio.com',
    storageBucket: 'desarrollocode.firebasestorage.app',
    measurementId: 'G-S75QV2LGXC',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCxvggr5wOl3_l8jX90JiAUoP2WWt6qOqo',
    appId: '1:702436046817:android:f0b1b7dbb32607e7e0c4a0',
    messagingSenderId: '702436046817',
    projectId: 'desarrollocode',
    databaseURL: 'https://desarrollocode-default-rtdb.firebaseio.com',
    storageBucket: 'desarrollocode.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC_3UrNt4-0kZs1NlT-_odfof_x2cZOMX0',
    appId: '1:702436046817:ios:310b40992e9d9ee3e0c4a0',
    messagingSenderId: '702436046817',
    projectId: 'desarrollocode',
    databaseURL: 'https://desarrollocode-default-rtdb.firebaseio.com',
    storageBucket: 'desarrollocode.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC_3UrNt4-0kZs1NlT-_odfof_x2cZOMX0',
    appId: '1:702436046817:ios:310b40992e9d9ee3e0c4a0',
    messagingSenderId: '702436046817',
    projectId: 'desarrollocode',
    databaseURL: 'https://desarrollocode-default-rtdb.firebaseio.com',
    storageBucket: 'desarrollocode.firebasestorage.app',
    iosBundleId: 'com.example.app2',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDc7TbSZnlZHp2muPb3HFa0l_OVGbTMsXA',
    appId: '1:702436046817:web:e9a894c6d1231549e0c4a0',
    messagingSenderId: '702436046817',
    projectId: 'desarrollocode',
    authDomain: 'desarrollocode.firebaseapp.com',
    databaseURL: 'https://desarrollocode-default-rtdb.firebaseio.com',
    storageBucket: 'desarrollocode.firebasestorage.app',
    measurementId: 'G-1NW35S5T96',
  );
}
